repos:
  - repo: https://github.com/psf/black
    rev: 21.7b1
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    - id: isort
